In [1]:
import numpy as np
import matplotlib.pyplot as plt


2.Можно ли к одному и тому же признаку применить сразу и нормализацию, и стандартизацию?

Да,можно

3.Напишите функцию наподобие eval_model_reg2, но для применения L1-регуляризации

In [2]:
X = np.array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
              [1, 1, 2, 5, 3, 0, 5, 10, 1, 2],
              [500, 700, 750, 600, 1450, 800, 1500, 2000, 450, 1000],
              [1, 1, 2, 1, 2, 1, 3, 3, 1, 2]])

In [3]:
y = [45, 55, 50, 55, 60, 35, 75, 80, 50, 60]

In [4]:
def calc_mse(y, y_pred):
    err = np.mean((y - y_pred)**2)
    return err

In [5]:
def standard_scale(X):
    mean = X.mean(axis=0)
    std = X.std(axis=0)
    return (X - mean) / std

In [6]:
X_st = X.copy().astype(np.float64)
X_st[:, 1:10] = standard_scale(X_st[:, 1:10])
X_st

array([[  1.        ,  -0.57735027,  -0.57940718,  -0.58249071,
         -0.57894479,  -0.57638682,  -0.58043426,  -0.58158972,
         -0.57735027,  -0.57889218],
       [  1.        ,  -0.57735027,  -0.57632113,  -0.5670349 ,
         -0.57575501,  -0.57927597,  -0.57426353,  -0.57117319,
         -0.57735027,  -0.57657893],
       [500.        ,   1.73205081,   1.73204943,   1.73201633,
          1.73204971,   1.7320496 ,   1.73204669,   1.73203785,
          1.73205081,   1.73205004],
       [  1.        ,  -0.57735027,  -0.57632113,  -0.58249071,
         -0.5773499 ,  -0.57638682,  -0.5773489 ,  -0.57927494,
         -0.57735027,  -0.57657893]])

In [32]:
def eval_model_regl1(X, y, iterations, alpha=0.00001, lambda_=0.000001):
    #np.random.seed(42)
    W = np.random.randn(X.shape[0])
    n = X.shape[1]
    for i in range(0, iterations):
        y_pred = np.dot(W, X)
        err = calc_mse(y, y_pred)
        W -= alpha * (1/n * 2 * np.dot((y_pred - y), X.T) + lambda_ * np.sign(W)) 
      #  if i % (iterations /10) == 0:
        #    print(i, W, err)
    return W

In [33]:
eval_model_regl1(X_st,y,iterations=500, alpha=0.0001,lambda_=0.000001)

C:\Users\79094\AppData\Local\Temp/ipykernel_27956/1493808047.py:2: RuntimeWarning: overflow encountered in square
  err = np.mean((y - y_pred)**2)


array([-3.53866600e+298, -3.53913622e+298, -1.80199950e+301,
       -3.53882041e+298])

 1 Постройте график зависимости весов всех признаков от lambda в L2-регуляризации на основе данных из урока.

In [34]:
lbm=[]
norm=[]
lb=0.01
for i in range(0, 10):
    
    w=eval_model_regl1(X_st,y,iterations=500, alpha=0.0001,lambda_=lb)
    b=np.linalg.norm(w, ord=None)
    norm.append(b)
    lbm.append(lb)
    lb=lb/10
    print(b)
    print(w)
    print(norm)
    print(lb)

inf
[-2.08728305e+298 -2.08756041e+298 -1.06290987e+301 -2.08737414e+298]
[inf]
0.001
inf
[2.98404337e+298 2.98443990e+298 1.51956830e+301 2.98417359e+298]
[inf, inf]
0.0001
inf
[-2.14403436e+298 -2.14431926e+298 -1.09180941e+301 -2.14412792e+298]
[inf, inf, inf]
1e-05
inf
[-2.39985112e+297 -2.40017001e+297 -1.22207931e+300 -2.39995584e+297]
[inf, inf, inf, inf]
1.0000000000000002e-06
inf
[-3.08810732e+297 -3.08851767e+297 -1.57256092e+300 -3.08824208e+297]
[inf, inf, inf, inf, inf]
1.0000000000000002e-07
inf
[2.12421903e+298 2.12450130e+298 1.08171883e+301 2.12431172e+298]
[inf, inf, inf, inf, inf, inf]
1.0000000000000002e-08
inf
[2.60166999e+298 2.60201570e+298 1.32485180e+301 2.60178352e+298]
[inf, inf, inf, inf, inf, inf, inf]
1.0000000000000003e-09
inf
[-6.01559114e+297 -6.01639050e+297 -3.06332732e+300 -6.01585364e+297]
[inf, inf, inf, inf, inf, inf, inf, inf]
1.0000000000000003e-10
inf
[-2.25475481e+298 -2.25505443e+298 -1.14819173e+301 -2.25485320e+298]
[inf, inf, inf, inf, inf

C:\Users\79094\AppData\Local\Temp/ipykernel_27956/1493808047.py:2: RuntimeWarning: overflow encountered in square
  err = np.mean((y - y_pred)**2)
